Create training endpoint
jakefoster954/KainosSprint pull request #66
Opened 2021-07-21 15:15 UTC by bbell-99

Implement endpoint for retrieving training data per band level

2021-07-21 15:19 UTC, jakefoster954 requested changes

2021-07-21 15:19 UTC, jakefoster954 commented on src/main/java/com/kainos/ea/DTO.java
> +                "SELECT trainingName, trainingLink FROM KainosSprint.Training \n" +
Can you just use <space key> instead of \n please. SQL queries can be executed as one line which is the convention we have used everywhere else

2021-07-21 15:41 UTC, jakefoster954 approved these changes

2021-07-22 08:15 UTC, LaurenDant approved these changes

2021-07-22 08:43 UTC, merged